import { KungFu } from '../model/base';

export const schoolIcons: { [k in KungFu]: string } = {
    花间游: 'wanhua/skill-1',
    离经易道: 'wanhua/skill-2',
    冰心诀: 'qixiu/skill-1',
    云裳心经: 'qixiu/skill-2',
    毒经: 'wudu/skill-1',
    补天诀: 'wudu/skill-2',
    莫问: 'changge/skill-1',
    相知: 'changge/skill-2',
    傲血战意: 'tiance/skill-1',
    铁牢律: 'tiance/skill-2',
    易筋经: 'shaolin/skill-1',
    洗髓经: 'shaolin/skill-2',
    焚影圣诀: 'mingjiao/skill-1',
    明尊琉璃体: 'mingjiao/skill-2',
    分山劲: 'cangyun/skill-1',
    铁骨衣: 'cangyun/skill-2',
    紫霞功: 'chunyang/skill-1',
    太虚剑意: 'chunyang/skill-2',
    惊羽诀: 'tangmen/skill-1',
    天罗诡道: 'tangmen/skill-2',
    山居剑意: 'cangjian/skill-1',
    问水诀: 'cangjian/skill-2',
    北傲诀: 'badao/skill-1',
    凌海诀: 'penglai/skill-1',
    太玄经: 'yantian/skill-1',
    笑尘诀: 'gaibang/skill-1',
    隐龙诀: 'lingxue/skill-1',
};
